FROM ubuntu:latest

RUN apt update

RUN apt -y upgrade

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get install -y git

RUN apt install -y default-jre

RUN apt install -y default-jdk

RUN apt install -y python3-pip

RUN apt install -y build-essential
